apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "lsc.fullname" . }}
  labels:
    {{- include "lsc.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "lsc.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "lsc.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "lsc.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          args: ["{{ .Values.syncTaskName }}","{{ .Values.asyncTaskName }}"]
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          env:
            - name: JAVA_OPTS
              value: "-Xms512m -Xmx1024m -Dcom.sun.jndi.ldap.object.disableEndpointIdentification=true"
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default (printf "v%s" .Chart.AppVersion) }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          livenessProbe:
            exec:
              command:
                - sh
                - -c
                - "ps aux | grep '[j]ava.*lsc' >/dev/null 2>&1"
            initialDelaySeconds: 30
            periodSeconds: 60
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: config
              mountPath: /usr/local/lsc/etc/lsc.xml
              subPath: lsc.xml
            - name: config
              mountPath: /usr/local/lsc/etc/logback.xml
              subPath: logback.xml
            - name: ca-certs
              mountPath: /usr/local/lsc/certs
              readOnly: true
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: config
          configMap:
            name: {{ include "lsc.fullname" . }}-config
        - name: ca-certs
          secret:
            secretName: {{ include "lsc.fullname" . }}-ca-certs
            optional: true 
